In [1]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
from surprise import Dataset, Reader
from surprise import SVD, SVDpp, BaselineOnly

from surprise.model_selection import train_test_split
from surprise.model_selection import cross_validate

In [3]:
from scipy.sparse import csr_matrix

from implicit.als import AlternatingLeastSquares
from implicit.lmf import LogisticMatrixFactorization

In [4]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_rows', 30)

In [5]:
random_state_value = 42

id_column_name = 'common_id_2'
rating_column_name = 'rating'

**Загружаем датасет**

In [4]:
from google.colab import drive
drive.mount('/content/drive')

ModuleNotFoundError: No module named 'google'

In [6]:
data_dir = 'Data_Rabota'

In [7]:
train_df = pd.read_parquet(f"{data_dir}/Processed_dataset.parquet")
train_df

,common_id,event_date,event_timestamp,action_time,vacancy_id_,cookie_id,user_id,event_type,common_id_2
15,2,2022-09-05,1662374899,0.0,192850,0000d7508334414ca792c5ff66eb8c14,None,preview_click_vacancy,0000d7508334414ca792c5ff66eb8c14
16,2,2022-09-05,1662374899,498.0,192850,0000d7508334414ca792c5ff66eb8c14,None,show_vacancy,0000d7508334414ca792c5ff66eb8c14
17,2,2022-09-05,1662375397,1.0,230581,0000d7508334414ca792c5ff66eb8c14,None,preview_click_vacancy,0000d7508334414ca792c5ff66eb8c14
18,2,2022-09-05,1662375398,205.0,230581,0000d7508334414ca792c5ff66eb8c14,None,show_vacancy,0000d7508334414ca792c5ff66eb8c14
19,2,2022-09-05,1662375603,1.0,250327,0000d7508334414ca792c5ff66eb8c14,None,preview_click_vacancy,0000d7508334414ca792c5ff66eb8c14
...,...,...,...,...,...,...,...,...,...
12292571,367640,2022-09-26,1664169217,1.0,197828,ffffd6d4f2134dd6aa80ff71e942b508,82a5e80f91b144f596496d6d831b49d3,preview_click_vacancy,82a5e80f91b144f596496d6d831b49d3
12292572,367640,2022-09-26,1664169218,90.0,197828,ffffd6d4f2134dd6aa80ff71e942b508,82a5e80f91b144f596496d6d831b49d3,show_vacancy,82a5e80f91b144f596496d6d831b49d3
12292573,367640,2022-09-26,1664169308,210911.0,197828,ffffd6d4f2134dd6aa80ff71e942b508,82a5e80f91b144f596496d6d831b49d3,click_contacts,82a5e80f91b144f596496d6d831b49d3
12292574,367640,2022-09-28,1664380219,132.0,233452,ffffd6d4f2134dd6aa80ff71e942b508,82a5e80f91b144f596496d6d831b49d3,click_contacts,82a5e80f91b144f596496d6d831b49d3
12292575,367640,2022-09-28,1664380351,0.0,230870,ffffd6d4f2134dd6aa80ff71e942b508,82a5e80f91b144f596496d6d831b49d3,click_contacts,82a5e80f91b144f596496d6d831b49d3

In [8]:
test_df = pd.read_parquet(f"{data_dir}/test_public_mfti.parquet")
test_df

,cookie_id,vacancy_id_
0,000cd76cd33f43d4a1ac1d16d10f8bf7,"[222177, 222173, 222163, 238874, 238878, 228125, 225604, 235544, 119314]"
1,0034bc7f404341ba8412665453e7825a,"[102794, 137587, 257319, 237756, 240744, 113482, 240245, 221376, 242642, 235561, 191512, 222762, 231446, 109269, 205578]"
2,00a6c5a64a274c55a836402bdeb3b2c4,"[254292, 164602, 116438, 228634, 218819, 240655, 240659, 237341, 176563, 255299, 245637, 109275, 111505, 212953, 217549, 207108, 200475, 211355, 211449, 108956, 111071, 253239, 109649, 221735, 222030, 222174, 231207, 231022, 234380, 106944, 203948, 175325, 193534, 197505, 234769, 238933, 225709, 184466, 242642, 203015]"
3,015937a125b14e74bdff1cddc49f9172,"[246685, 138123, 115420, 210628, 212325, 235196]"
4,01de50c280794cec8804f16f45f847b7,"[219070, 251469, 166899, 212703, 214561]"
...,...,...
767,fdbcda17f22f406486837059e76c7fed,"[207851, 254989, 213344, 214180, 222146]"
768,fe6193ab26494ace9be5aae36e507618,"[115352, 230546, 225527, 120188, 109360, 232128, 237590, 259570, 244126, 229677, 135447]"
769,fe95b2826ee1452b81201ed3f4c3294d,"[240362, 114852, 253946, 251081, 127546, 244688]"
770,ff1aef256a49481698bb2e938510ff36,"[231194, 236363, 220747, 244688, 100094, 240521, 179568, 184858, 100103]"
771,ff40591f76e34013a61b8af400002a07,"[100336, 116442, 244721, 256719, 230803]"

In [9]:
nonrel_act_list = ['show_vacancy',
                'preview_click_vacancy',
                'click_favorite',
                'preview_click_favorite']

rel_act_list = ['click_response',
                'preview_click_response',
                'click_contacts',
                'preview_click_contacts',
                'click_phone',
                'preview_click_phone']

In [10]:
def get_top_n_vacancies(rating_act_list, pos_vacancies_start=0, pos_vacancies_end=100):
    show_act = train_df[train_df['event_type'].isin(rating_act_list)].groupby('vacancy_id_')['event_type'].count()
    top_n_with_event_quant = show_act.sort_values(ascending=False).iloc[pos_vacancies_start:pos_vacancies_end].to_frame().reset_index()
    return top_n_with_event_quant['vacancy_id_'].unique()

In [11]:
# ТОП-80 для рейтинга по просмотрам

vac_start = 0
vac_end = 80
rating_act = ['show_vacancy']

top80vac = get_top_n_vacancies(rating_act,
                               pos_vacancies_start=vac_start,
                               pos_vacancies_end=vac_end)
top80vac

array([260154, 198114, 203404, 202608, 116823, 164602, 207423, 148714,
       111505, 182870, 250327, 111867, 110421, 108242, 242642, 217683,
       258441, 158242, 162187, 174953, 176141, 207108, 247535, 110792,
       237341, 113305, 240744, 149024, 244077, 113482, 180382, 114583,
       182100, 113707, 105907, 210628, 227708, 110793, 247276, 181745,
       164481, 193331, 246509, 243868, 190030, 153245, 138634, 169194,
       115924, 126251, 164588, 154411, 155539, 120252, 230707, 127352,
       214513, 182084, 249571, 207156, 168935, 239021, 184440, 106944,
       187360, 206350, 117525, 111592, 150283, 253678, 112506, 117532,
       220718, 151616, 109079, 111837, 136266, 164246, 182439, 111890],
      dtype=int64)

In [12]:
# ТОП-200 для рейтинга по просмотрам

vac_start = 0
vac_end = 200
rating_act = ['show_vacancy']

top200vac = get_top_n_vacancies(rating_act,
                                pos_vacancies_start=vac_start,
                                pos_vacancies_end=vac_end)
top200vac

array([260154, 198114, 203404, 202608, 116823, 164602, 207423, 148714,
       111505, 182870, 250327, 111867, 110421, 108242, 242642, 217683,
       258441, 158242, 162187, 174953, 176141, 207108, 247535, 110792,
       237341, 113305, 240744, 149024, 244077, 113482, 180382, 114583,
       182100, 113707, 105907, 210628, 227708, 110793, 247276, 181745,
       164481, 193331, 246509, 243868, 190030, 153245, 138634, 169194,
       115924, 126251, 164588, 154411, 155539, 120252, 230707, 127352,
       214513, 182084, 249571, 207156, 168935, 239021, 184440, 106944,
       187360, 206350, 117525, 111592, 150283, 253678, 112506, 117532,
       220718, 151616, 109079, 111837, 136266, 164246, 182439, 111890,
       257631, 143721, 248852, 171332, 128183, 140917, 111941, 212141,
       102794, 212325, 229689, 258378, 106293, 176171, 129787, 181275,
       190928, 242560, 195702, 191512, 144113, 209568, 219681, 197930,
       239624, 128278, 230322, 221108, 171602, 154423, 205606, 209422,
       248720, 173337, 114328, 187662, 201312, 198348, 200506, 121184,
       115977, 176131, 173648, 242814, 153970, 192565, 221349, 179082,
       207211, 221419, 253833, 154568, 196428, 162851, 246570, 228572,
       206544, 117897, 132005, 178135, 103881, 168781, 106943, 195403,
       109685, 176046, 141487, 142619, 244994, 125867, 153944, 230326,
       193250, 152046, 149354, 232857, 119337, 239318, 186617, 221920,
       103713, 101396, 138123, 134147, 257871, 182289, 106626, 127052,
       101194, 212027, 113018, 252289, 104276, 241134, 109157, 212953,
       247299, 230467, 219770, 164236, 161649, 137659, 173350, 140813,
       182173, 192562, 124853, 101410, 107882, 133079, 210503, 212987,
       140184, 173659, 242145, 184628, 176285, 240663, 150516, 207302],
      dtype=int64)

In [13]:
# ТОП-1000 для рейтинга по просмотрам

vac_start = 0
vac_end = 1000
rating_act = ['show_vacancy']

top1000vac = get_top_n_vacancies(rating_act,
                                pos_vacancies_start=vac_start,
                                pos_vacancies_end=vac_end)
top1000vac

array([260154, 198114, 203404, 202608, 116823, 164602, 207423, 148714,
       111505, 182870, 250327, 111867, 110421, 108242, 242642, 217683,
       258441, 158242, 162187, 174953, 176141, 207108, 247535, 110792,
       237341, 113305, 240744, 149024, 244077, 113482, 180382, 114583,
       182100, 113707, 105907, 210628, 227708, 110793, 247276, 181745,
       164481, 193331, 246509, 243868, 190030, 153245, 138634, 169194,
       115924, 126251, 164588, 154411, 155539, 120252, 230707, 127352,
       214513, 182084, 249571, 207156, 168935, 239021, 184440, 106944,
       187360, 206350, 117525, 111592, 150283, 253678, 112506, 117532,
       220718, 151616, 109079, 111837, 136266, 164246, 182439, 111890,
       257631, 143721, 248852, 171332, 128183, 140917, 111941, 212141,
       102794, 212325, 229689, 258378, 106293, 176171, 129787, 181275,
       190928, 242560, 195702, 191512, 144113, 209568, 219681, 197930,
       239624, 128278, 230322, 221108, 171602, 154423, 205606, 209422,
       248720, 173337, 114328, 187662, 201312, 198348, 200506, 121184,
       115977, 176131, 173648, 242814, 153970, 192565, 221349, 179082,
       207211, 221419, 253833, 154568, 196428, 162851, 246570, 228572,
       206544, 117897, 132005, 178135, 103881, 168781, 106943, 195403,
       109685, 176046, 141487, 142619, 244994, 125867, 153944, 230326,
       193250, 152046, 149354, 232857, 119337, 239318, 186617, 221920,
       103713, 101396, 138123, 134147, 257871, 182289, 106626, 127052,
       101194, 212027, 113018, 252289, 104276, 241134, 109157, 212953,
       247299, 230467, 219770, 164236, 161649, 137659, 173350, 140813,
       182173, 192562, 124853, 101410, 107882, 133079, 210503, 212987,
       140184, 173659, 242145, 184628, 176285, 240663, 150516, 207302,
       137702, 119363, 102305, 199540, 101228, 169048, 246285, 182382,
       158697, 214814, 124698, 253817, 115420, 257051, 162315, 246556,
       240347, 101136, 183704, 183466, 259663, 104640, 245952, 191293,
       142214, 171623, 209448, 198751, 195356, 209245, 250385, 145456,
       178415, 148686, 195787, 182877, 166590, 122614, 106676, 148118,
       107073, 168918, 164702, 142565, 123518, 220670, 145573, 259394,
       151497, 195860, 257747, 200685, 230145, 107830, 180398, 106729,
       188595, 215913, 187383, 106165, 228655, 123270, 104155, 253239,
       172737, 175239, 143204, 112618, 189920, 207560, 181751, 207435,
       207169, 106208, 149530, 111071, 225096, 132050, 191508, 107242,
       116900, 252188, 149034, 204957, 185913, 171981, 183638, 146630,
       158496, 256132, 251534, 181976, 209629, 146444, 126019, 196308,
       205479, 191382, 200472, 252384, 217549, 218967, 119437, 195073,
       219266, 258466, 124917, 249792, 106664, 256216, 165933, 234319,
       181878, 173016, 156861, 215939, 203569, 231500, 113088, 146757,
       138622, 257047, 156108, 115589, 101462, 167238, 173179, 244389,
       172483, 149415, 242710, 184032, 202663, 191702, 141489, 182846,
       111193, 243795, 130474, 128816, 127887, 234115, 204370, 185926,
       102896, 103018, 123467, 161133, 149284, 190471, 185197, 133324,
       114223, 222378, 139376, 205911, 138424, 241040, 185354, 104799,
       115696, 256534, 207444, 163708, 163625, 165274, 177818, 114918,
       136872, 197244, 193243, 150476, 244318, 139187, 119015, 234795,
       136514, 190032, 199017, 256498, 257171, 177622, 153469, 101450,
       141630, 115308, 185355, 154033, 190025, 240432, 254643, 145455,
       178874, 118104, 133932, 115560, 105190, 116793, 219253, 182879,
       172903, 171415, 211897, 106584, 119367, 114852, 165670, 159495,
       225472, 210469, 239623, 224389, 176398, 161721, 132492, 216948,
       202516, 117263, 131347, 137318, 171261, 109245, 108625, 107526,
       206841, 246134, 163098, 257899, 245804, 114102, 196789, 253946,
       177710, 219755, 136817, 155517, 218223, 258458, 154943, 176291,
       248871, 195637, 250129, 248107, 246450, 247647, 217242, 255046,
       205630, 256536, 118276, 195053, 124555, 259320, 113575, 192850,
       120845, 166835, 242115, 210229, 174728, 259923, 113630, 198998,
       160547, 248568, 219951, 145782, 107949, 108005, 230077, 233227,
       112313, 222886, 132616, 201053, 149366, 243398, 146566, 248010,
       206155, 200544, 180145, 125869, 173832, 166516, 189317, 153678,
       214119, 260161, 221281, 182317, 190472, 219948, 178041, 197991,
       154248, 116433, 215169, 147154, 159568, 120891, 227347, 213155,
       117640, 119806, 178942, 135430, 203690, 246363, 182350, 158963,
       170871, 114244, 100431, 182679, 147325, 167493, 208781, 127706,
       123591, 173384, 188336, 173897, 105890, 160132, 173015, 171080,
       175174, 216704, 237692, 127335, 155280, 244659, 157500, 198088,
       115220, 254514, 252853, 148600, 218108, 145067, 137711, 151763,
       178040, 119302, 123085, 228253, 235614, 136038, 102919, 212293,
       225500, 112819, 109069, 143013, 174224, 125585, 230419, 227068,
       230875, 108852, 102255, 151635, 164728, 160421, 132841, 159361,
       214466, 198503, 136044, 259050, 198131, 177174, 112780, 178208,
       154356, 207356, 106801, 243575, 126489, 113820, 127221, 206340,
       178143, 256041, 144034, 110030, 204066, 117912, 227727, 215620,
       181884, 169462, 115587, 208761, 246149, 120188, 198005, 171734,
       214226, 108536, 236890, 243678, 109360, 179657, 133138, 139737,
       149484, 196406, 154491, 156844, 245637, 134834, 202624, 237288,
       259480, 105877, 146479, 171425, 217535, 244467, 232245, 161249,
       109275, 112920, 171878, 243003, 162381, 204199, 129996, 116438,
       128484, 231653, 141571, 252269, 173014, 183555, 152160, 108331,
       188468, 138889, 125452, 165064, 107611, 194792, 252965, 213244,
       256527, 182682, 180144, 192158, 253947, 144097, 102273, 104013,
       181353, 247304, 239569, 256548, 222410, 160305, 103209, 253956,
       154580, 201190, 251535, 241653, 212300, 193574, 248331, 213822,
       156721, 224538, 111706, 253976, 211355, 113322, 178225, 145829,
       242898, 168263, 189345, 126965, 113472, 183958, 210301, 142299,
       167761, 143301, 128292, 142316, 146062, 102219, 137696, 108201,
       112069, 248293, 203903, 135755, 113670, 197407, 238292, 190285,
       110315, 253241, 160206, 101147, 168634, 110571, 137630, 182640,
       138483, 149416, 101097, 200593, 139152, 166799, 119539, 228516,
       110713, 120893, 100458, 108063, 137156, 209840, 193816, 198112,
       245609, 224441, 156517, 153586, 160244, 258955, 257474, 108924,
       177654, 195228, 205010, 193142, 108889, 126548, 117475, 105974,
       241598, 130482, 140688, 186595, 225976, 191816, 196591, 117104,
       182262, 164889, 142787, 215523, 138017, 125652, 216093, 175424,
       188575, 146724, 218072, 130142, 207442, 200901, 204473, 213150,
       108241, 122122, 213173, 248723, 179156, 217559, 183457, 133376,
       226122, 109959, 243583, 161460, 217894, 226698, 189998, 189816,
       153104, 108033, 252639, 253671, 113217, 190511, 251823, 127524,
       258660, 239620, 196306, 176963, 208454, 108347, 192590, 173148,
       223752, 119693, 198095, 105129, 162857, 166931, 140535, 113383,
       160630, 137642, 133127, 128062, 112333, 256790, 127588, 237786,
       211189, 258036, 241030, 216004, 134872, 178853, 252464, 246815,
       155208, 257000, 189469, 104004, 219886, 141916, 140092, 161485,
       118693, 241786, 232976, 117354, 160473, 184671, 217606, 106775,
       153214, 102532, 203273, 173683, 255563, 146865, 101013, 214678,
       141563, 145705, 194451, 141452, 180146, 258519, 103429, 229515,
       151937, 102359, 235677, 125295, 102552, 117759, 258751, 176433,
       174723, 200613, 144215, 131821, 249437, 243690, 129198, 206907,
       129510, 184286, 177973, 231017, 182079, 219082, 126291, 231114,
       173306, 149417, 196383, 168114, 222030, 153475, 194853, 104528,
       189778, 249418, 114685, 101349, 181653, 182385, 220073, 133356,
       175567, 206211, 121955, 198956, 128312, 147538, 208607, 135494,
       157060, 154408, 243915, 251704, 227048, 108374, 137068, 115609,
       163065, 115748, 222703, 203115, 212332, 115548, 181844, 253045,
       251569, 129442, 178095, 239932, 104844, 112255, 110533, 187474,
       143718, 105847, 159582, 108410, 174102, 252883, 219841, 172345,
       209746, 106046, 227451, 205749, 199899, 150321, 179522, 200575,
       254312, 159332, 225865, 101240, 113656, 237425, 126137, 245705,
       250672, 145361, 159276, 195694, 159563, 126180, 122139, 137971,
       187101, 108732, 257379, 202607, 228075, 186365, 177700, 137407,
       119568, 217896, 156440, 227071, 118383, 248535, 232724, 244140,
       139986, 206150, 107561, 153459, 187740, 227207, 113816, 106580,
       179533, 132139, 252161, 157786, 170382, 218040, 223476, 105548,
       174638, 206602, 142012, 101354, 135416, 145268, 149831, 157421],
      dtype=int64)

In [14]:
# Топ вакансий с 10 до 95

vac_start = 10
vac_end = 95
rating_act = ['show_vacancy']

top95vac_from10 = get_top_n_vacancies(rating_act,
                                                      pos_vacancies_start=vac_start,
                                                      pos_vacancies_end=vac_end)
top95vac_from10

array([250327, 111867, 110421, 108242, 242642, 217683, 258441, 158242,
       162187, 174953, 176141, 207108, 247535, 110792, 237341, 113305,
       240744, 149024, 244077, 113482, 180382, 114583, 182100, 113707,
       105907, 210628, 227708, 110793, 247276, 181745, 164481, 193331,
       246509, 243868, 190030, 153245, 138634, 169194, 115924, 126251,
       164588, 154411, 155539, 120252, 230707, 127352, 214513, 182084,
       249571, 207156, 168935, 239021, 184440, 106944, 187360, 206350,
       117525, 111592, 150283, 253678, 112506, 117532, 220718, 151616,
       109079, 111837, 136266, 164246, 182439, 111890, 257631, 143721,
       248852, 171332, 128183, 140917, 111941, 212141, 102794, 212325,
       229689, 258378, 106293, 176171, 129787], dtype=int64)

In [15]:
# Создаем колонку с типом действия для рейтинга
# 1 - целевое действие, 0 - остальные действия

def check_is_purpose(event):
    if event in rel_act_list:
        return 1
    else:
        return 0

train_df[rating_column_name] = train_df['event_type'].apply(check_is_purpose)
train_df

,common_id,event_date,event_timestamp,action_time,vacancy_id_,cookie_id,user_id,event_type,common_id_2,rating
15,2,2022-09-05,1662374899,0.0,192850,0000d7508334414ca792c5ff66eb8c14,None,preview_click_vacancy,0000d7508334414ca792c5ff66eb8c14,0
16,2,2022-09-05,1662374899,498.0,192850,0000d7508334414ca792c5ff66eb8c14,None,show_vacancy,0000d7508334414ca792c5ff66eb8c14,0
17,2,2022-09-05,1662375397,1.0,230581,0000d7508334414ca792c5ff66eb8c14,None,preview_click_vacancy,0000d7508334414ca792c5ff66eb8c14,0
18,2,2022-09-05,1662375398,205.0,230581,0000d7508334414ca792c5ff66eb8c14,None,show_vacancy,0000d7508334414ca792c5ff66eb8c14,0
19,2,2022-09-05,1662375603,1.0,250327,0000d7508334414ca792c5ff66eb8c14,None,preview_click_vacancy,0000d7508334414ca792c5ff66eb8c14,0
...,...,...,...,...,...,...,...,...,...,...
12292571,367640,2022-09-26,1664169217,1.0,197828,ffffd6d4f2134dd6aa80ff71e942b508,82a5e80f91b144f596496d6d831b49d3,preview_click_vacancy,82a5e80f91b144f596496d6d831b49d3,0
12292572,367640,2022-09-26,1664169218,90.0,197828,ffffd6d4f2134dd6aa80ff71e942b508,82a5e80f91b144f596496d6d831b49d3,show_vacancy,82a5e80f91b144f596496d6d831b49d3,0
12292573,367640,2022-09-26,1664169308,210911.0,197828,ffffd6d4f2134dd6aa80ff71e942b508,82a5e80f91b144f596496d6d831b49d3,click_contacts,82a5e80f91b144f596496d6d831b49d3,1
12292574,367640,2022-09-28,1664380219,132.0,233452,ffffd6d4f2134dd6aa80ff71e942b508,82a5e80f91b144f596496d6d831b49d3,click_contacts,82a5e80f91b144f596496d6d831b49d3,1
12292575,367640,2022-09-28,1664380351,0.0,230870,ffffd6d4f2134dd6aa80ff71e942b508,82a5e80f91b144f596496d6d831b49d3,click_contacts,82a5e80f91b144f596496d6d831b49d3,1

In [16]:
# Готовим датафрейм для обучения модели:

train_matrix = train_df.groupby([id_column_name, 'vacancy_id_'], as_index=False)[rating_column_name].sum()
train_matrix

                              common_id_2  vacancy_id_  rating
0        000089d26cdd49d68839c68bc10f2cf2       177380       0
1        000089d26cdd49d68839c68bc10f2cf2       181353       0
2        000089d26cdd49d68839c68bc10f2cf2       195890       0
3        000089d26cdd49d68839c68bc10f2cf2       205562       0
4        000089d26cdd49d68839c68bc10f2cf2       211064       0
...                                   ...          ...     ...
4707502  ffffdb17f45b4032b386d691d52e6c00       107125       1
4707503  ffffdb17f45b4032b386d691d52e6c00       107893       1
4707504  ffffdb17f45b4032b386d691d52e6c00       150843       1
4707505  ffffdb17f45b4032b386d691d52e6c00       160164       1
4707506  ffffdb17f45b4032b386d691d52e6c00       185412       1

[4707507 rows x 3 columns]

In [17]:
# Функция для создания рейтинга на основе порогового значения для целевых действий

def create_rating(input_rating, thresholds):
    rating = input_rating
    if rating >= max(rating_thresholds):
        rating = thresholds[max(rating_thresholds)]
    else:
        rating = thresholds[rating_thresholds[rating]]
    return rating

In [18]:
# Создаем рейтинг
# Принципы построения
# 1. rating >= 1 - rating = 1
# 2. rating = 0 - оставляем без изменения

rating_thresholds = {0: 0, 1: 1}

train_matrix_0_1 = train_matrix.copy()
train_matrix_0_1[rating_column_name] = train_matrix_0_1[rating_column_name].apply(create_rating, thresholds = rating_thresholds)
train_matrix_0_1
train_matrix_0_1[rating_column_name].unique()

array([0, 1], dtype=int64)

In [19]:
# Готовим данные для обучения модели

reader = Reader(rating_scale=(0, 1))
train_data_0_1 = Dataset.load_from_df(train_matrix_0_1[[id_column_name, 'vacancy_id_', rating_column_name]], reader)

In [20]:
# Обучаем модель для датасета с рейтингом 0 или 1

svd_20epochs_0_1 = SVD(verbose=True, n_epochs=20)
trainset_0_1 = train_data_0_1.build_full_trainset()
svd_20epochs_0_1.fit(trainset_0_1)

Processing epoch 0
Processing epoch 1
Processing epoch 2
Processing epoch 3
Processing epoch 4
Processing epoch 5
Processing epoch 6
Processing epoch 7
Processing epoch 8
Processing epoch 9
Processing epoch 10
Processing epoch 11
Processing epoch 12
Processing epoch 13
Processing epoch 14
Processing epoch 15
Processing epoch 16
Processing epoch 17
Processing epoch 18
Processing epoch 19

In [21]:
col_names ={
    'id_col_name': id_column_name,
    'vac_col_name': 'vacancy_id_',
    'rating_col_name': rating_column_name
}

In [23]:
def transform_into_sparse_matrix(input_df, col_names):
    input_df_fixed = input_df.copy()
    input_df_fixed[col_names['id_col_name']] = input_df_fixed[col_names['id_col_name']].astype('category')
    input_df_fixed[col_names['vac_col_name']] = input_df_fixed[col_names['vac_col_name']].astype('category')
    input_df_fixed[col_names['rating_col_name']] = input_df_fixed[col_names['rating_col_name']].astype('uint8')
    user_item_matrix = csr_matrix((input_df_fixed[col_names['rating_col_name']], 
                                (input_df_fixed[col_names['id_col_name']].cat.codes, 
                                 input_df_fixed[col_names['vac_col_name']].cat.codes)))
    id_cat_codes = dict(zip(input_df_fixed[col_names['id_col_name']], input_df_fixed[col_names['id_col_name']].cat.codes))
    vac_cat_codes = dict(zip(input_df_fixed[col_names['vac_col_name']], input_df_fixed[col_names['vac_col_name']].cat.codes))
    cat_vac_codes = dict(zip(input_df_fixed[col_names['vac_col_name']].cat.codes, input_df_fixed[col_names['vac_col_name']]))
    return (user_item_matrix, id_cat_codes, vac_cat_codes, cat_vac_codes)

In [24]:
Impl_0_1_set = transform_into_sparse_matrix(train_matrix_0_1, col_names)

In [25]:
Impl_ALS_0_1 = AlternatingLeastSquares(factors=100,
                                       regularization=0.05,
                                       calculate_training_loss=True,
                                       random_state=random_state_value) # , alpha=3.0
Impl_ALS_0_1.fit(Impl_0_1_set[0])

  0%|          | 0/15 [00:00<?, ?it/s]

In [46]:
id_column_name

'common_id_2'

In [41]:
def common_for_cookie(cookie_id, n_predict = 5):
    """Функция для определения common_id от cookie_id для обучения рекомендательной системы"""
    common_freq = train_df[train_df['cookie_id'] == cookie_id][id_column_name].value_counts(normalize=True)
    common_ids = {com_id: round(freq*n_predict) for com_id, freq in zip(common_freq.index.to_list(), common_freq.to_list())}
    return common_ids

In [42]:
# Вспомогательные функции

def get_predictions(cookie_id, model_info, initial_set, n_predict = 5):     
    model = model_info[0]
    model_type = model_info[1]  

    top_n_vacancies = []
    common_ids = common_for_cookie(cookie_id)    
    for com_id, n in common_ids.items():
        if n != 0:
            # Получим все вакансии с которыми взаимодействовал cookie_id:
            interacted_items = train_matrix[train_matrix[id_column_name] == com_id]['vacancy_id_'].unique()
            
            # Удалим из этого перечня вакансии с которыми контактировал юзер:
            items_to_predict = np.setdiff1d(initial_set, interacted_items)
            
            # получим топ-n вакансий для данного юзера:
            if model_type == 'surprise':
                new_top_n_vac = get_predictions_surprise(com_id, model, items_to_predict, n)  
            
            if model_type == 'implicit':
                filtered_set = train_matrix[~train_matrix['vacancy_id_'].isin(items_to_predict)]['vacancy_id_'].unique()
                new_top_n_vac = get_predictions_implicit(com_id, model, filtered_set, model_info[2], n)
            top_n_vacancies.extend(new_top_n_vac)
    
    return top_n_vacancies

def get_predictions_surprise(user_id, model, vac_set, n_predict = 5):
    # Создадим тест датасет для данного юзера:
    test_set = [[user_id, item, 4.] for item in vac_set]        
    
    predictions = model.test(test_set)
    top_n = sorted(predictions, key=lambda x: x.est, reverse=True)[:n_predict]
    return [pred.iid for pred in top_n]

def get_predictions_implicit(user_id, model, filtered_set, impl_set, n_predict = 5):
    user_item = impl_set[0]
    id_cat_code = impl_set[1][user_id]
    vac_cat_codes = impl_set[2]
    cat_vac_codes = impl_set[3]
    filter_items = np.array([vac_cat_codes[i] for i in filtered_set])
    ids, scores = model.recommend(id_cat_code,
                                  user_item[id_cat_code],
                                  N=n_predict,
                                  filter_items=filter_items,
                                  filter_already_liked_items=True)
    return [cat_vac_codes[i] for i in ids]    

def calc_correct_recomend_number(predict_col, vac_col):
    """Функция для определения количества совпадающих вакансий в двух списках"""
    return len(set(predict_col) & set(vac_col))


def common_for_cookie(cookie_id, n_predict = 5):
    """Функция для определения common_id от cookie_id для обучения рекомендательной системы"""
    common_freq = train_df[train_df['cookie_id'] == cookie_id].common_id.value_counts(normalize=True)
    common_ids = {com_id: round(freq*n_predict) for com_id, freq in zip(common_freq.index.to_list(), common_freq.to_list())}
    return common_ids


def get_prec_n(res_df, num_corr_column, n_predict = 5):
    """Функция для расчета precision@n метрики"""
    corr_recommend = res_df[num_corr_column].sum()
    prec_5 = corr_recommend / (n_predict * res_df.shape[0])
    return {'num_corr_recomend': corr_recommend, f'precision@{n_predict}': prec_5}

In [28]:
# Копируем датасет чтобы не менять изначальный

test_df_with_pred = test_df.copy()

In [29]:
# Задаем словари с моделями и датасетами чтобы перебрать их все

models_dict = {
    'SVD_20ep_rat0-1': [svd_20epochs_0_1, 'surprise'],
}

set_dict = {
    'top80': top80vac,
    'top95_10': top95vac_from10
}

In [43]:
# Импортируем tqdm для progress bar
from tqdm.auto import tqdm

def get_res_df(models_dict, set_dict, n_predict = 5):
    res_dict = {}
    for model_name in tqdm(models_dict):        
        for set_name in tqdm(set_dict):        
            # Создаем столбец с предсказаниями
            predict_col_name = f'predict_id_{model_name}_{set_name}_n_{n_pred}'            
            test_df_with_pred[predict_col_name] = test_df_with_pred['cookie_id'].apply(get_predictions,
                                                                                       model_info = models_dict[model_name],
                                                                                       initial_set = set_dict[set_name],
                                                                                       n_predict = n_pred)                  
            
            # Создаем столбец с количеством правильных предсказаний для каждого id
            num_corr_col_name = f'num_corr_{model_name}_{set_name}_n_{n_pred}'        
            test_df_with_pred[num_corr_col_name] = test_df_with_pred.apply(
                lambda x: calc_correct_recomend_number(x[predict_col_name], x['vacancy_id_']), axis=1
            )
            
            # Считаем precision@n метрику
            res_dict[model_name+'_'+set_name] = get_prec_n(test_df_with_pred,
                                                           num_corr_column = num_corr_col_name,
                                                           n_predict = n_pred)
    return pd.DataFrame.from_dict(res_dict, orient='index')

In [31]:
n_pred = 5

res_df = get_res_df(models_dict, set_dict, n_predict = n_pred)
res_df

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

                          num_corr_recomend  precision@5
SVD_20ep_rat0-1_top80                    26     0.006736
SVD_20ep_rat0-1_top95_10                 91     0.023575

In [32]:
# Создание списка неактульных вакансий, с которомы давно не было взаимодействий
# 78 973 вакансии не были провзаимодействованы за последние 2 недели рассматриваемого периода (prec = 0.031)
# 99 046 вакансии не были провзаимодействованы за последнюю неделю (prec = 0.033)
# 117 944 вакансии не были провзаимодействованы за последние 3 дня (prec = 0.036)
# 127 405 вакансии не были провзаимодействованы за последние 2 дня (prec = 0.038)
# 140 242 вакансии не были провзаимодействованы за последний 1 день - 0.04
non_valid_vacs = []
for vac, group in train_df.groupby('vacancy_id_'):
    max_date = group['event_date'].max()
    if max_date <= '2022-09-30':
        non_valid_vacs.append(vac)
len(non_valid_vacs)

140242

In [33]:
valid_vacs = train_matrix[~train_matrix['vacancy_id_'].isin(non_valid_vacs)]['vacancy_id_'].unique()
len(valid_vacs)

19925

In [44]:
# Задаем словари с моделями и датасетами чтобы перебрать их все

models_dict = {
    'Impl_ALS_rat0-1': [Impl_ALS_0_1, 'implicit', Impl_0_1_set]
}

set_dict = {
    'top200': top200vac,
    'top1000': top1000vac,
    'non_val_vacs': valid_vacs
}

In [45]:
n_pred = 5

res_df = get_res_df(models_dict, set_dict, n_predict = n_pred)
res_df

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/3 [00:00<?, ?it/s]

KeyError: 63

In [ ]:
pd.set_option('display.max_rows', None)
res_df.sort_values(by=['precision@5'], ascending=False)